name: 'test dotnet nuget'

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: debug1
      run: |
        dotnet --list-sdks
        dotnet nuget --version

    - name: .NET Core 3.1.x SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: debug2
      run: |
        dotnet --list-sdks
        dotnet nuget --version

    - name: .NET 5.x SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: debug3
      run: |
        dotnet --list-sdks
        dotnet nuget --version

